YountanYargyas/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/django', admin.site.urls),
    path('', include('main.urls')),
    path('tinymce/', include('tinymce.urls')),
]

main/urls.py
from django.urls import path
from . import views
from django.conf.urls.static import static
from django.conf import settings

app_name = "main"

urlpatterns = [
    path("", views.homepage, name="homepage"),
    path("about/", views.aboutpage, name="aboutpage"),
    path("contact/", views.contactpage, name="contactpage"),
    path("help/", views.helppage, name="helppage"),
    path("register/", views.register, name="register"),
    path("login/", views.login_request, name="login_request"),
    path("change-password/", views.change_password, name="change_password"),
    path("logout/", views.logout_request, name="logout"),
    path("profile/", views.profile, name="profile"),
    path("admin/", views.admin_section, name="admin_section"),
    # path("upload/", views.upload, name="upload"),
    # path("upload/images", views.upload_images, name="upload_images"),
    # path("upload/videos", views.upload_videos, name="upload_videos"),
    # path("upload/audios", views.upload_audios, name="upload_audios"),
    # path("upload/files", views.upload_files, name="upload_files"),
    path("assembly/", views.assembly, name="assembly"),
    path("community/", views.community_feed, name="community_feed"),
    path("community/feed", views.cf_feed, name="cf_feed"),
    path("community/profiles", views.cf_profiles, name="cf_profiles"),
    path("community/profiles/<slug:username_slug>", views.cf_profile_posts, name="cf_profile_posts"),
    path("community/posts", views.cf_posts, name="cf_posts"),
    # path("messages/", views.messages_section, name="messages_section"),
    # path("messages/<slug:username_slug>", views.messages_chat, name="messages_chat"),
    # path("notifications/", views.notifications, name="notifications"),
    path("classes/", views.student_classes, name="student_classes"),
    path("classes/<slug:class_slug>", views.student_class, name="student_class"),
    path("classes/<slug:class_slug>/<slug:subject_slug>", views.student_subject, name="student_subject"),
    path("classes/<slug:class_slug>/<slug:subject_slug>/<slug:chapter_slug>", views.student_chapter, name="student_chapter"),
    path("classes/<slug:class_slug>/<slug:subject_slug>/<slug:chapter_slug>/<slug:section_slug>", views.student_section, name="student_section"),
    path("student/", views.student_categories, name="student_categories"),
    path("student/<slug:category_slug>", views.student_content, name="student_content"),
    path("delete-data", views.delete_data, name="delete_data"),
    path("edit-data", views.edit_data, name="edit_data"),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

main/models.py
from django.db import models
from datetime import datetime

from django.core.exceptions import ValidationError
from django.utils.text import slugify
from django.conf import settings
from os.path import splitext

import random
import string

# Create your models here.

class StudentClass(models.Model):
    student_class = models.CharField(max_length=100)
    class_summary = models.CharField(max_length=500, blank=True, null=True)
    # Image/Media to be added later
    class_slug = models.SlugField(max_length=100)

    class Meta:
        verbose_name_plural = "Classes"

    def validate_unique(self, *args, **kwargs):
        self.class_slug = slugify(self.student_class) if slugify(self.student_class) else slugify(''.join(random.choices(string.ascii_lowercase + string.digits, k=10)))
        super(StudentClass, self).validate_unique(*args, **kwargs)
        if self.__class__.objects.filter(class_slug=self.class_slug).exists():
            raise ValidationError(message=f"Class with name \"{self.student_class}\" already exists.",
                                  code='unique_together',)

    def __str__(self):
        return self.student_class

class StudentSubject(models.Model):
    student_subject = models.CharField(max_length=100)
    subject_summary = models.CharField(max_length=500, blank=True, null=True)
    # Image/Media to be added later
    subject_slug = models.SlugField(max_length=100)

    student_class = models.ForeignKey(StudentClass, default=1, verbose_name="Class", on_delete=models.SET_DEFAULT)

    class Meta:
        verbose_name_plural = "Subjects"

    def validate_unique(self, *args, **kwargs):
        self.subject_slug = slugify(self.student_subject) if slugify(self.student_subject) else slugify(''.join(random.choices(string.ascii_lowercase + string.digits, k=10)))
        super(StudentSubject, self).validate_unique(*args, **kwargs)
        if self.__class__.objects.filter(subject_slug=self.subject_slug, student_class__class_slug=self.student_class.class_slug).exists():
            raise ValidationError(message=f"Subject with name \"{self.student_subject}\" already exists.",
                                  code='unique_together',)

    def __str__(self):
        return self.student_subject

class StudentChapter(models.Model):
    student_chapter = models.CharField(max_length=100)
    chapter_summary = models.CharField(max_length=500, blank=True, null=True)
    # Image/Media to be added later
    chapter_slug = models.SlugField(max_length=100)

    student_subject = models.ForeignKey(StudentSubject, default=1, verbose_name="Subject", on_delete=models.SET_DEFAULT)

    class Meta:
        verbose_name_plural = "Chapters"

    def validate_unique(self, *args, **kwargs):
        self.chapter_slug = slugify(self.student_chapter) if slugify(self.student_chapter) else slugify(''.join(random.choices(string.ascii_lowercase + string.digits, k=10)))
        super(StudentChapter, self).validate_unique(*args, **kwargs)
        if self.__class__.objects.filter(chapter_slug=self.chapter_slug, student_subject__subject_slug=self.student_subject.subject_slug, student_subject__student_class__class_slug=self.student_subject.student_class.class_slug).exists():
            raise ValidationError(message=f"Chapter with name \"{self.student_chapter}\" already exists.",
                                  code='unique_together',)

    def __str__(self):
        return self.student_chapter

class StudentSection(models.Model):
    def user_directory_path(instance, filename):
        return f"{instance.section_video_base}{instance.section_slug}.{filename.split('.')[-1]}"

    student_section = models.CharField(max_length=100)
    section_summary = models.CharField(max_length=500, blank=True, null=True)
    section_slug = models.SlugField(max_length=100)

    section_file = models.FileField(upload_to=user_directory_path, blank=True, null=True)
    section_file_base = models.CharField(max_length=300)
    section_text = models.TextField(blank=True, null=True)

    student_chapter = models.ForeignKey(StudentChapter, default=1, verbose_name="Chapter", on_delete=models.SET_DEFAULT)

    class Meta:
        verbose_name_plural = "Sections"

    def validate_unique(self, *args, **kwargs):
        self.section_slug = slugify(self.student_section) if slugify(self.student_section) else slugify(''.join(random.choices(string.ascii_lowercase + string.digits, k=10)))
        super(StudentSection, self).validate_unique(*args, **kwargs)
        if self.__class__.objects.filter(section_slug=self.section_slug, student_chapter__chapter_slug=self.student_chapter.chapter_slug, student_chapter__student_subject__subject_slug=self.student_chapter.student_subject.subject_slug, student_chapter__student_subject__student_class__class_slug=self.student_chapter.student_subject.student_class.class_slug).exists():
            raise ValidationError(message=f"Section with name \"{self.student_section}\" already exists.",
                                  code='unique_together',)

    def file_type(self):
        name, extension = splitext(self.section_file.name.lower())
        if extension in ['.apng', '.avif', '.gif', '.jpg', '.jpeg', '.jfif', '.pjpeg', '.pjp', '.png', '.svg', '.webp']:
            return 'image'
        elif extension in ['.mp4', '.webm', '.3gp']:
            return 'video'
        elif extension in ['.mp3', '.wav', '.ogg', '.m4a']:
            return 'audio'
        else:
            return 'file'

    def delete(self, *args, **kwargs):
        if self.section_file:
            self.section_file.storage.delete(self.section_file.name)
        super(StudentSection, self).delete(*args, **kwargs)

    def __str__(self):
        return self.student_section

class StudentCategory(models.Model):
    def user_directory_path(instance, filename):
        return f"student/content/{instance.category_slug}/{instance.category_slug}.{filename.split('.')[-1]}"

    student_category = models.CharField(max_length=100)
    category_summary = models.CharField(max_length=500, blank=True, null=True)
    category_slug = models.SlugField(max_length=100)

    category_image = models.FileField(upload_to=user_directory_path)

    class Meta:
        verbose_name_plural = "Categories"

    def validate_unique(self, *args, **kwargs):
        self.category_slug = slugify(self.student_category) if slugify(self.student_category) else slugify(''.join(random.choices(string.ascii_lowercase + string.digits, k=10)))
        super(StudentCategory, self).validate_unique(*args, **kwargs)
        if self.__class__.objects.filter(category_slug=self.category_slug).exists():
            raise ValidationError(message=f"Category with name \"{self.student_category}\" already exists.",
                                  code='unique_together',)

    def delete(self, *args, **kwargs):
        if self.category_image:
            self.category_image.storage.delete(self.category_image.name)
        super(StudentCategory, self).delete(*args, **kwargs)

    def __str__(self):
        return self.student_category

class StudentContent(models.Model):
    def user_directory_path(instance, filename):
        return f"student/content/{instance.content_category.category_slug}/{slugify(instance.student_content) if slugify(instance.student_content) else slugify(''.join(random.choices(string.ascii_lowercase + string.digits, k=10)))}.{filename.split('.')[-1]}"

    student_content = models.CharField(max_length=100)
    content_text = models.TextField()
    content_time = models.DateTimeField(auto_now_add=True)
    content_file = models.FileField(upload_to=user_directory_path, blank=True, null=True)

    content_user = models.ForeignKey(settings.AUTH_USER_MODEL, verbose_name="User", on_delete=models.CASCADE)
    content_category = models.ForeignKey(StudentCategory, verbose_name="Category", on_delete=models.CASCADE)

    class Meta:
        verbose_name_plural = "Content"

    def file_type(self):
        name, extension = splitext(self.content_file.name.lower())
        if extension in ['.apng', '.avif', '.gif', '.jpg', '.jpeg', '.jfif', '.pjpeg', '.pjp', '.png', '.svg', '.webp']:
            return 'image'
        elif extension in ['.mp4', '.webm', '.3gp']:
            return 'video'
        elif extension in ['.mp3', '.wav', '.ogg', '.m4a']:
            return 'audio'
        else:
            return 'file'

    def delete(self, *args, **kwargs):
        if self.content_file:
            self.content_file.storage.delete(self.content_file.name)
        super(StudentContent, self).delete(*args, **kwargs)

    def __str__(self):
        return self.student_content

class UploadImage(models.Model):
    def user_directory_path(instance, filename):
        return f"upload/images/{slugify(instance.image_name) if slugify(instance.image_name) else slugify(''.join(random.choices(string.ascii_lowercase + string.digits, k=10)))}.{filename.split('.')[-1]}"

    image_name = models.CharField(max_length=100)
    image_summary = models.CharField(max_length=500, blank=True, null=True)

    image_file = models.FileField(upload_to=user_directory_path)

    class Meta:
        verbose_name_plural = "Images"

    def delete(self, *args, **kwargs):
        if self.image_file:
            self.image_file.storage.delete(self.image_file.name)
        super(UploadImage, self).delete(*args, **kwargs)

    def __str__(self):
        return self.image_name

class UploadVideo(models.Model):
    def user_directory_path(instance, filename):
        return f"upload/videos/{slugify(instance.video_name) if slugify(instance.video_name) else slugify(''.join(random.choices(string.ascii_lowercase + string.digits, k=10)))}.{filename.split('.')[-1]}"

    video_name = models.CharField(max_length=100)
    video_summary = models.CharField(max_length=500, blank=True, null=True)

    video_file = models.FileField(upload_to=user_directory_path)

    class Meta:
        verbose_name_plural = "Videos"

    def delete(self, *args, **kwargs):

main/templates/main/change_password.html
{% extends "main/includes/header.html" %}

{% block content %}
    <div class="z-depth-1">
        <ul class="breadcrumbs">
            <li><a href="/">Home</a></li>
            <li><a href="/profile">Profile</a></li>
            <li><b>Change Password</b></li>
        </ul>
    </div>

    <div class="card card-panel grey lighten-5 z-depth-1">
        <h3 align="center">Change Password</h3>
        <div class="divider"></div>
        <p>
            <form method="POST">
                {% csrf_token %}
                {{ form.as_p }}
                <p style="display: flex; justify-content: center;"><button type="submit" class="btn">Change Password</button></p>
            </form>
        </p>
    </div>
{% endblock %}

main/templates/main/edit-data.html
{% extends "main/includes/header.html" %}

{% block content %}
    <div class="card card-panel grey lighten-5 z-depth-1">
        <h3 align="center">{{ title }}</h3>
        <div class="divider"></div>
        <p>
            <form action="/edit-data" method="POST">
                {% csrf_token %}
                {{ form.as_p }}
                <p style="display: flex; justify-content: center;"><button type="submit" class="btn">{{ title }}</button></p>
            </form>
        </p>
    </div>
{% endblock %}

main/templates/main/profile.html
{% extends "main/includes/header.html" %}

{% block content %}
    <div class="z-depth-1">
        <ul class="breadcrumbs">
            <li><a href="/">Home</a></li>
            <li><b>Profile</b></li>
        </ul>
    </div>

    <div class="card card-panel grey lighten-5 z-depth-1">
        <h3 align="center">{{ user.username }}</h3>
        <div class="divider"></div>
        <table class="highlight centered">
            <tbody>
                <tr>
                    <td>Username</td>
                    <td>{{ user.username }}</td>
                </tr>
                <tr>
                    <td>Joined</td>
                    <td>{{ user.date_joined|date:"M d, Y" }}</td>
                </tr>
            </tbody>
        </table>
        <p>
            <div align="center">
                <a href="/change-password" class="btn waves-light"><i class="material-icons left">lock</i>Change Password</a>
            </div>
        </p>
    </div>
{% endblock %}

main/templates/main/student-categories.html
{% extends "main/includes/header.html" %}
{% load static %}

{% block content %}
    <div class="z-depth-1">
        <ul class="breadcrumbs">
            <li><a href="/">Home</a></li>
            <li><b>Student Section</b></li>
        </ul>
    </div>

    {% if monitor %}
        <ul class="collapsible">
            <li>
                <div class="collapsible-header grey lighten-5 z-depth-1"><i class="material-icons">add</i><big>Add Category</big></div>
                <div class="collapsible-body">
                    <form method="POST" enctype="multipart/form-data" id="upload_progress_form">
                        {% csrf_token %}
                        {{ form.as_p }}
                        <p><label style="margin-right: 25px;">Thumbnail:</label><label for="id_category_image" class="btn">Choose Image</label></p>
                        <p style="display: flex; justify-content: center;"><button type="submit" class="btn" id="upload_progress_button">Add Category</button></p>
                    </form>
                </div>
            </li>
        </ul>
        <script type="text/javascript">
            var uploadField = document.getElementById("id_category_image");
            uploadField.onchange = function() {
                if(this.files[0].size > (5*1048576)) {
                   alert("Max Thumbnail Size is 5 MB");
                   this.value = "";
                };
            };
        </script>
    {% endif %}

    <div class="row">
        {% for category in student_categories %}
            <a href="/student/{{ category.category_slug }}" style="display: block; color: inherit; text-decoration: inherit;">
                <div class="col s12 m6 l4">
                    <div class="card">
                        <div class="card-image" style="position: relative; width: 100%; padding-top: 56.25%">
                            <img src="{% if category.category_image %}{{ category.category_image.url }}{% endif %}" style="position: absolute; object-fit: cover; max-width: 100%; max-height: 100%; magrin: 0 auto;">
                            <div style="position: absolute; top: 0; left: 0; width: 100%; height: 100%; box-shadow: inset 0px -70px 100px -10px #000000;"></div>
                            <span class="card-title"><b>{{ category.student_category }}</b></span>
                            <a href="#modal{{ forloop.counter }}i" class="btn-floating halfway-fab waves-effect waves-light red modal-trigger"><i class="material-icons">info_outline</i></a>
                        </div>
                        <div class="card-content">
                            <p style="display: -webkit-box; -webkit-line-clamp: 1; -webkit-box-orient: vertical; overflow: hidden; height: 1.5em; line-height: 1.5;">{{ category.category_summary }}</p>
                        </div>
                        {% if monitor %}
                            <div class="card-action" align="center">
                                <form action="/edit-data" method="POST" style="display: inline;">
                                    {% csrf_token %}
                                    <input type="hidden" name="data_type" value="student-category">
                                    <input type="hidden" name="data_id" value="{{ category.id }}">
                                    <input type="hidden" name="data_next" value="{{ next }}">
                                    <button type="submit" class="btn waves-light"><i class="material-icons left">edit</i>Edit</button>
                                </form>
                                <a href="#modal{{ forloop.counter }}" class="modal-trigger btn orange darken-4"><i class="material-icons left">delete</i>Delete</a>
                            </div>
                            <div id="modal{{ forloop.counter }}" class="modal">
                                <div class="modal-content">
                                    <h4>Confirmation</h4>
                                    <p>Are you sure you want to delete this category?</p>
                                </div>
                                <div class="modal-footer">
                                    <form action="/delete-data" method="POST" style="display: inline;">
                                        {% csrf_token %}
                                        <input type="hidden" name="data_type" value="student-category">
                                        <input type="hidden" name="data_id" value="{{ category.id }}">
                                        <input type="hidden" name="data_next" value="{{ next }}">
                                        <button type="submit" class="waves-effect waves-red btn-flat">Yes</button>
                                    </form>
                                    <button href="#!" class="modal-close waves-effect waves-green btn-flat">No</button>
                                </div>
                            </div>
                        {% endif %}
                    </div>
                </div>
            </a>
            <div id="modal{{ forloop.counter }}i" class="modal">
                <div class="modal-content">
                    <h4>{{ category.student_category }}</h4>
                    <p>{{ category.category_summary|linebreaks }}</p>
                </div>
                <div class="modal-footer">
                    <a href="#!" class="modal-close waves-effect waves-green btn-flat">Close</a>
                </div>
            </div>
        {% empty %}
            <div class="card card-panel grey lighten-5 z-depth-1" align="center">
                <span class="card-title"><b>This section is empty!</b></span>
            </div>
        {% endfor %}
    </div>
{% endblock %}

main/templates/main/upload-images.html
{% extends "main/includes/header.html" %}
{% load static %}

{% block content %}
    <div class="z-depth-1">
        <ul class="breadcrumbs">
            <li><a href="/">Home</a></li>
            <li>Upload</li>
            <li><b>Images</b></li>
        </ul>
    </div>

    <div class="row grey lighten-5 z-depth-1" align="center">
        <div class="col s3 m3 l3 upload-bar" style="padding-top: 15px; padding-bottom: 15px; background-color: #dadada;"><b>Images</b></div>
        <a href="/upload/videos" style="display: block; color: inherit; text-decoration: inherit;">
            <div class="col s3 m3 l3 upload-bar" style="padding-top: 15px; padding-bottom: 15px;"><b>Videos</b></div>
        </a>
        <a href="/upload/audios" style="display: block; color: inherit; text-decoration: inherit;">
            <div class="col s3 m3 l3 upload-bar" style="padding-top: 15px; padding-bottom: 15px;"><b>Audios</b></div>
        </a>
        <a href="/upload/files" style="display: block; color: inherit; text-decoration: inherit;">
            <div class="col s3 m3 l3 upload-bar" style="padding-top: 15px; padding-bottom: 15px;"><b>Files</b></div>
        </a>
    </div>

    {% if editor %}
        <ul class="collapsible">
            <li>
                <div class="collapsible-header grey lighten-5 z-depth-1"><i class="material-icons">add</i><big>Upload Image</big></div>
                <div class="collapsible-body">
                    <form method="POST" enctype="multipart/form-data" id="upload_progress_form">
                        {% csrf_token %}
                        {{ form.as_p }}
                        <p><label style="margin-right: 25px;">Image:</label><label for="id_image_file" class="btn">Choose Image</label></p>
                        <p style="display: flex; justify-content: center;"><button type="submit" class="btn" id="upload_progress_button">Upload Image</button></p>
                    </form>
                </div>
            </li>
        </ul>
        <script type="text/javascript">
            var uploadField = document.getElementById("id_image_file");
            uploadField.onchange = function() {
                if(this.files[0].size > (25*1048576)) {
                   alert("Max Image Size is 25 MB");
                   this.value = "";
                };
            };
        </script>
    {% endif %}

    <div class="row">
        {% for image in page_obj %}
            <div class="col s12 m6 l4">
                <div class="card">
                    <div class="card-image" style="position: relative; width: 100%; padding-top: 56.25%">
                        <img src="{% if image.image_file %}{{ image.image_file.url }}{% endif %}" style="position: absolute; object-fit: cover; max-width: 100%; max-height: 100%; magrin: 0 auto;">
                        <div style="position: absolute; top: 0; left: 0; width: 100%; height: 100%; box-shadow: inset 0px -70px 100px -10px #000000;"></div>
                        <span class="card-title"><b>{{ image.image_name }}</b></span>
                        <a href="#modal{{ forloop.counter }}i" class="btn-floating halfway-fab waves-effect waves-light red modal-trigger"><i class="material-icons">info_outline</i></a>
                    </div>
                    <div class="card-content">
                        <p style="display: -webkit-box; -webkit-line-clamp: 1; -webkit-box-orient: vertical; overflow: hidden; height: 1.5em; line-height: 1.5;">{{ image.image_summary }}</p>
                    </div>
                    <div class="card-action" align="center">
                        <input type="text" value="{% if image.image_file %}{{ image.image_file.url }}{% endif %}" disabled>
                        <a id="copy-button-{{ forloop.counter }}" class="btn tooltipped" data-position="bottom" data-tooltip="Click to Copy!" onclick="copyToClipboard('{% if image.image_file %}{{ image.image_file.url }}{% endif %}', '{{ forloop.counter }}')">Copy Link</a>
                        <a {% if image.image_file %}href="{{ image.image_file.url }}"{% endif %} class="btn tooltipped" data-position="bottom" data-tooltip="Click to Download!">Download</a>
                    </div>
                    {% if editor %}
                        <div class="card-action" align="center">
                            <form action="/edit-data" method="POST" style="display: inline;">
                                {% csrf_token %}
                                <input type="hidden" name="data_type" value="image">
                                <input type="hidden" name="data_id" value="{{ image.id }}">
                                <input type="hidden" name="data_next" value="{{ next }}">
                                <button type="submit" class="btn waves-light"><i class="material-icons left">edit</i>Edit</button>
                            </form>
                            <a href="#modal{{ forloop.counter }}" class="modal-trigger btn orange darken-4"><i class="material-icons left">delete</i>Delete</a>
                        </div>
                        <div id="modal{{ forloop.counter }}" class="modal">
                            <div class="modal-content">
                                <h4>Confirmation</h4>
                                <p>Are you sure you want to delete this image?</p>
                            </div>
                            <div class="modal-footer">
                                <form action="/delete-data" method="POST" style="display: inline;">
                                    {% csrf_token %}
                                    <input type="hidden" name="data_type" value="image">
                                    <input type="hidden" name="data_id" value="{{ image.id }}">
                                    <input type="hidden" name="data_next" value="{{ next }}">
                                    <button type="submit" class="waves-effect waves-red btn-flat">Yes</button>
                                </form>
                                <button href="#!" class="modal-close waves-effect waves-green btn-flat">No</button>
                            </div>
                        </div>
                    {% endif %}
                </div>
            </div>
            <div id="modal{{ forloop.counter }}i" class="modal">
                <div class="modal-content">
                    <h4>{{ image.image_name }}</h4>
                    <p>{{ image.image_summary|linebreaks }}</p>
                </div>
                <div class="modal-footer">
                    <a href="#!" class="modal-close waves-effect waves-green btn-flat">Close</a>
                </div>
            </div>
        {% empty %}
            <div class="card card-panel grey lighten-5 z-depth-1" align="center">
                <span class="card-title"><b>This section is empty!</b></span>
            </div>
        {% endfor %}
    </div>

    {% if page_obj %}
        <div align="center">
            <ul class="pagination">
                {% if page_obj.has_previous %}
                    <li class="waves-effect"><a href="?page=1"><i class="material-icons">first_page</i></a></li>
                    <li class="waves-effect"><a href="?page={{ page_obj.previous_page_number }}"><i class="material-icons">chevron_left</i></a></li>
                {% else %}
                    <li class="disabled"><a><i class="material-icons">first_page</i></a></li>
                    <li class="disabled"><a><i class="material-icons">chevron_left</i></a></li>
                {% endif %}
                {% if page_obj.number|add:'-2' > 0 %}
                    <li class="waves-effect"><a href="?page={{ page_obj.number|add:'-2' }}">{{ page_obj.number|add:'-2' }}</a></li>
                {% endif %}
                {% if page_obj.number|add:'-1' > 0 %}
                    <li class="waves-effect"><a href="?page={{ page_obj.number|add:'-1' }}">{{ page_obj.number|add:'-1' }}</a></li>
                {% endif %}
                <li class="active"><a>{{ page_obj.number }}</a></li>
                {% if page_obj.number|add:'1' <= page_obj.paginator.num_pages %}
                    <li class="waves-effect"><a href="?page={{ page_obj.number|add:'1' }}">{{ page_obj.number|add:'1' }}</a></li>
                {% endif %}
                {% if page_obj.number|add:'2' <= page_obj.paginator.num_pages %}
                    <li class="waves-effect"><a href="?page={{ page_obj.number|add:'2' }}">{{ page_obj.number|add:'2' }}</a></li>
                {% endif %}
                {% if page_obj.has_next %}
                    <li class="waves-effect"><a href="?page={{ page_obj.next_page_number }}"><i class="material-icons">chevron_right</i></a></li>
                    <li class="waves-effect"><a href="?page={{ page_obj.paginator.num_pages }}"><i class="material-icons">last_page</i></a></li>
                {% else %}
                    <li class="disabled"><a><i class="material-icons">chevron_right</i></a></li>
                    <li class="disabled"><a><i class="material-icons">last_page</i></a></li>
                {% endif %}
            </ul>
        </div>
    {% endif %}

    <script>
        function copyToClipboard(textToCopy, idToChange) {
            document.querySelectorAll(".material-tooltip .tooltip-content")[2*idToChange-2].innerHTML = "Copied!";
            // document.getElementById("copy-button-"+idToChange).setAttribute("data-tooltip", "Copied!");
            // navigator clipboard api needs a secure context (https)
            if (navigator.clipboard && window.isSecureContext) {
                // navigator clipboard api method'
                return navigator.clipboard.writeText(textToCopy);
            } else {
                // text area method
                let textArea = document.createElement("textarea");
                textArea.value = textToCopy;
                // make the textarea out of viewport
                textArea.style.position = "absolute";
                textArea.style.opacity = 0;
                document.body.appendChild(textArea);
                textArea.select();
                return new Promise((res, rej) => {
                    document.execCommand('copy') ? res() : rej();
                    textArea.remove();
                });
            }
        }
    </script>
{% endblock %}